set(cvg_sim_gazebo_plugins_MESSAGE_FILES "")
set(cvg_sim_gazebo_plugins_SERVICE_FILES "/home/jerryrain/ardrone_simulator/src/ardrone_rrt_gazebo_simulator/ardrone_simulator_gazebo7/cvg_sim_gazebo_plugins/srv/SetBias.srv")
